# Generated by Django 2.2.7 on 2019-12-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0003_auto_20191201_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeof',
            name='description',
        ),
    ]
