# Generated by Django 2.2.7 on 2019-12-01 17:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0004_remove_typeof_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WodExercices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('metrics', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crossfit.Mouvement')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='mouvements',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='type',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercices',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='log',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='log',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='mouvements',
        ),
        migrations.AlterField(
            model_name='score',
            name='score_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wod',
            name='description_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Exercices',
        ),
        migrations.DeleteModel(
            name='RestPause',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.AddField(
            model_name='wod',
            name='exercices',
            field=models.ManyToManyField(to='crossfit.WodExercices'),
        ),
    ]
