# Generated by Django 3.0 on 2020-01-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0005_auto_20191201_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='WodHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wod', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='done',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
    ]
