# Generated by Django 3.0 on 2020-01-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0006_auto_20200112_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossFitWebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WodScraping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wod', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='WodHistory',
        ),
    ]
