# Generated by Django 3.0 on 2020-01-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0007_auto_20200126_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='wodscraping',
            name='url',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='crossfit.CrossFitWebSite'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wodscraping',
            unique_together={('date', 'url')},
        ),
    ]
