# Generated by Django 3.0 on 2020-01-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0008_auto_20200126_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wodscraping',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crossfit.CrossFitWebSite'),
        ),
    ]
